apiVersion: sources.eventing.knative.dev/v1alpha1
kind: ContainerSource
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: http-to-knative-rgwpubsub
  namespace: rgwpubsub
spec:
  image: docker.io/yuvalif/rgwpubsub-knative-http-to-knative
  args:
    - '--subscriptionname=<subscription for acking>'
    - '--username=<user name>'
    - '--zonegroup=<zone group>'
    - '--port=<internal listening port>'
  env:
   - name: S3_ACCESS_KEY_ID
     value: '<rgw access key>'
   - name: S3_SECRET_ACCESS_KEY
     value: '<rgw secret key>'
   - name: S3_HOSTNAME
     value: '<rgw pubsub URL>'
  sink:
    apiVersion: eventing.knative.dev/v1alpha1
    kind: Channel
    name: rgw-ps-channel
