#!/bin/bash
echo "// Code generated by $0; DO NOT EDIT." > secret_vars.go
echo "package main" >> secret_vars.go
echo "" >> secret_vars.go
echo "var (" >> secret_vars.go
echo -e "\tgoogleVisionAPIKey = \"$GOOGLE_VISION_API_KEY\"" >> secret_vars.go
echo -e "\ts3AccessID         = \"$S3_ACCESS_KEY_ID\"" >> secret_vars.go
echo -e "\ts3AccessKey        = \"$S3_SECRET_ACCESS_KEY\"" >> secret_vars.go
echo -e "\ts3Endpoint         = \"$S3_HOSTNAME\"" >> secret_vars.go
echo ")" >> secret_vars.go
